FitLifeProLatest/force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>FLP-M-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>District__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OMR</fullName>
            </value>
            <value>
                <fullName>Navalur</fullName>
            </value>
            <value>
                <fullName>Guindy</fullName>
            </value>
            <value>
                <fullName>Saidapet</fullName>
            </value>
            <value>
                <fullName>Vadapalani</fullName>
            </value>
            <value>
                <fullName>Gandhipuram</fullName>
            </value>
            <value>
                <fullName>Saravanampatti</fullName>
            </value>
            <value>
                <fullName>R.S Puram</fullName>
            </value>
            <value>
                <fullName>Mettupalayam</fullName>
            </value>
            <value>
                <fullName>Perur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Membership_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_End_Date__c</fullName>
    <formula>IF(
ISPICKVAL(  Subscription_Type__c  , &#39;Monthly&#39;), 
 Membership_Start_Date__c  +30, 
IF(
ISPICKVAL( Subscription_Type__c  , &#39;Quarterly&#39;), 
 Membership_Start_Date__c  +90,
 Membership_Start_Date__c +365)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership End Date</label>
    <type>Date</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Membership_Plan__c.field-meta.xml
<CustomField>
    <fullName>Membership_Plan__c</fullName>
    <label>Membership Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot__c</fullName>
    <label>Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/PDFGenerateCtrl.cls
public class PDFGenerateCtrl {
    public Member__c con{get;set;}
    public String currentRecordId{get;set;}
 
    public PDFGenerateCtrl(){
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        if(currentRecordId != null && String.isNotBlank(currentRecordId)){
            con = [SELECT Id, First_Name__c, Email__c,Area__c,Membership_Plan__c,Membership_Start_Date__c,Membership_End_Date__c,Time_Slot__c FROM Member__c WHERE Id =:currentRecordId];
        }
    }
 
    @AuraEnabled(cacheable=true)
    public static List<Member__c> fetchRecords(){
        try {
            List<Member__c> conList = new List<Member__c>();
 
            conList = [Select id, First_Name__c, Email__c,Area__c,Membership_Plan__c,Membership_Start_Date__c,Membership_End_Date__c,Time_Slot__c from Member__c];              
            return conList;
        } catch (Exception e) {
            System.debug('Exception: '+e.getMessage());
            return null;
        }
    }
 
    @AuraEnabled
    public static String sendPdf(String contactId) {
        PageReference pdf = new pagereference('/apex/ContactDataPDF?id='+contactId);
        pdf.getParameters().put('id', contactId);
     
        Blob body;
        try {
            // returns page as a PDF
            body = pdf.getContent();
        } catch (Exception e) {
            body = Blob.valueOf('data');
        }
 
        //insert content version
        ContentVersion CV = new ContentVersion();
        CV.Title = 'TechdicerContact.pdf';
        CV.PathOnClient = 'TechdicerContact.pdf';
        CV.VersionData = body;
        CV.FirstPublishLocationId = contactId;
        insert CV;
         
        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.setContentType('application/pdf');
        attach.setFileName('TechdicerContact.pdf');
        attach.Body = body;
 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'shankarece007@gmail.com'});
        mail.setSubject('Generate PDF from Apex Salesforce');
        mail.setHtmlBody('Generate PDF from Apex Salesforce');
        mail.setFileAttachments(new Messaging.EmailFileAttachment[] {attach}); 
        // Send the email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        return 'Email sent Successfully with PDF.';
    }
}