FitLifeProLatest/force-app/main/default/objects/Fitness_Class__c/Fitness_Class__c.object-meta.xml
<CustomObject>
    <label>Fitness Class</label>
    <nameField>
        <displayFormat>FC-{000}</displayFormat>
        <label>Fitness Class Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fitness Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Class__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Class__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/FitnessClassesControllerTest.cls
@isTest
public class FitnessClassesControllerTest {
    
    @isTest
    static void testListOfClasses() {
        // Create test data
        Date testDate = Date.newInstance(2023, 10, 23);
        time testtime =Time.newInstance(System.now().hour(), System.now().minute(), System.now().second(), 0);
        
        Fitness_Class__c testFitnessClass = new Fitness_Class__c(Date__c = testDate, Time__c = testtime, Activity__c = 'Yoga', Duration__c = '60', Available_Slots__c = 10, Booking__c = 'Book');
        insert testFitnessClass;
        Fitness_Class__c testFitnessClass1 = new Fitness_Class__c(Date__c = testDate, Time__c = testtime, Activity__c = 'Pilates', Duration__c = '60', Available_Slots__c =0, Booking__c = 'Book');
        insert testFitnessClass1;
        // Call the method to be tested
        String serializedRecords = FitnessClassesController.ListOfClasses(testDate);

        // Add assertions based on the expected behavior
        System.assertNotEquals(serializedRecords, null);
        // Add more assertions as per the expected behavior
    }

    @isTest
    static void testUpdateAvailableSlots() {
        // Create test data
        Fitness_Class__c testFitnessClass = new Fitness_Class__c(Activity__c = 'Yoga', Available_Slots__c = 5);
        insert testFitnessClass;
        
         Fitness_Class__c testFitnessClass1 = new Fitness_Class__c(Activity__c = 'Pilates', Available_Slots__c = 5);
        insert testFitnessClass1;

        // Call the method to be tested
        String result = FitnessClassesController.updateAvaliableSlots('Yoga');
        string result1 = FitnessClassesController.updateAvaliableSlots('Pilates');

        // Retrieve the updated record
        Fitness_Class__c updatedFitnessClass = [SELECT Available_Slots__c FROM Fitness_Class__c WHERE Id = :testFitnessClass.Id];

        // Add assertions based on the expected behavior
        System.assertEquals(result, 'Success');
        System.assertEquals(updatedFitnessClass.Available_Slots__c, 4);
        System.assertEquals(result1, 'Success');
        System.assertEquals(updatedFitnessClass.Available_Slots__c, 0);
        // Add more assertions as per the expected behavior
    }

}