FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/Fitness_Trainer__c.object-meta.xml
<CustomObject>
    <description>List of Gym Trainers for Fitlife Pro</description>
    <label>Fitness Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fitness Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Trainer Phone Number</description>
    <inlineHelpText>Phone number should be in numbers and can&#39;t exceed 10 digits</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/TrainerDetailsTestClass.cls
@isTest
public class TrainerDetailsTestClass {
@isTest
Public static void testGetTrainerListHandler() {
        
        List<Fitness_Trainer__c> trainers = new List<Fitness_Trainer__c>();
        for (Integer i = 0; i < 5; i++) {
            trainers.add(new Fitness_Trainer__c(
                Name = 'Trainer ' + i,
                Email__c = 'trainer' + i + '@gmail.com',
                Last_Name__c = 'Lastname ' + i,
                Phone_Number__c = '123456789' + i
             ));
        }
        insert trainers;
       List<Fitness_Trainer__c> result = TrainerController.getTrainerListHandler();
       System.assertEquals(5, result.size());
     }
}