FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/Fitness_Trainer__c.object-meta.xml
<CustomObject>
    <description>List of Gym Trainers for Fitlife Pro</description>
    <label>Fitness Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fitness Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Assigned_Members__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Members__c</fullName>
    <label>Assigned Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Availability_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Availability_Schedule__c</fullName>
    <inlineHelpText>Please select any one of the slot.</inlineHelpText>
    <label>Availability Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Working_Status__c.field-meta.xml
<CustomField>
    <fullName>Working_Status__c</fullName>
    <description>Trainer is active or not</description>
    <label>Working Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In-active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>FLP-M-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Fitness_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fitness Trainer</label>
    <referenceTo>Fitness_Trainer__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot__c</fullName>
    <label>Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/MemberRevisedTriggerHandler.cls
public class MemberRevisedTriggerHandler {
    
    //Trigger Name : MemberRevisedTrigger
    List<Member__c> triggerNew;
    List<Member__c> triggerOld;
    Map<Id,Member__c> triggerNewMap;
    Map<Id,Member__c> triggerOldMap;    
    
    public MemberRevisedTriggerHandler(){
        
        triggerNew = (List<Member__c>)Trigger.New; // type cast from SObject to Member__c
        triggerOld = (List<Member__c>)Trigger.Old;
        triggerNewMap = (Map<Id,Member__c>)Trigger.NewMap;
        triggerOldMap = (Map<Id,Member__c>)Trigger.OldMap;
    }
    
    public void doAction(){        
        
        SWITCH on Trigger.operationType{
            
            WHEN BEFORE_INSERT{
                assignTrainerToMember();  
            }
            WHEN AFTER_INSERT{
                assignedMemberCount(triggerNew);
            }            
            WHEN AFTER_UPDATE{
                assignedMemberCount(triggerNew);
            }   
            WHEN AFTER_DELETE{
                assignedMemberCount(triggerOld);
            }            
            WHEN AFTER_UNDELETE{
                assignedMemberCount(triggerNew);
            }             
        }
    }
    
    public void assignTrainerToMember(){        
        integer i = 0;
        system.debug('Inside assignTrainerToMember');
        List<Fitness_Trainer__c> trainerLst = [SELECT Id, Name, Assigned_Members__c 
                                               FROM Fitness_Trainer__c 
                                               WHERE Working_Status__c = 'Active' 
                                               AND Availability_Schedule__c =: triggerNew[0].Time_Slot__c
                                               ORDER BY Assigned_Members__c 
                                              ];
        
        for(Member__c member : triggerNew)
        {
            member.Fitness_Trainer__c = trainerLst[0].Id;            
        }  
    }
    
    
    public void assignedMemberCount(List<Member__c> memberLst)
    { 
        system.debug('Inside assignedMemberCount');
        set<Id> trainerIds = new set<Id>();
        for(Member__c member : memberLst){
           if(member.Fitness_Trainer__c != null){
                if(Trigger.isUpdate){                    
                    if(triggerOldMap.get(member.Id).Fitness_Trainer__c != member.Fitness_Trainer__c){
                            trainerIds.add(member.Fitness_Trainer__c);
                            trainerIds.add(triggerOldMap.get(member.Id).Fitness_Trainer__c);
                        }                    
                }else{
                    trainerIds.add(member.Fitness_Trainer__c);
                } 
           }else if(member.Fitness_Trainer__c == null && triggerOldMap.get(member.Id).Fitness_Trainer__c != null){
               trainerIds.add(triggerOldMap.get(member.Id).Fitness_Trainer__c);
           }
        }          
    
        if(trainerIds.size()>0){
            //system.debug('Trainer Ids : ' + trainerIds);
            //List<AggregateResult> memAggLst = [select count(id) memCount , Fitness_Trainer__c from member__c where Id in : trainerIds Group by Fitness_Trainer__c];
            List<Fitness_Trainer__c> trainerLst = [SELECT Id, Assigned_Members__c , 
                                                   (SELECT Id, Fitness_Trainer__c FROM Members__r) 
                                                   FROM Fitness_Trainer__c 
                                                   WHERE Id in : trainerIds 
                                                  ]; 
            List<Fitness_Trainer__c> newTrainerData = new List<Fitness_Trainer__c>();
            for(Fitness_Trainer__c trainerRecord : trainerLst){
                Fitness_Trainer__c trainer = new Fitness_Trainer__c();
                trainer.Assigned_Members__c = trainerRecord.Members__r.size();
                trainer.Id = (Id)trainerRecord.get('Id');
                newTrainerData.add(trainer);
            }
            if(!newTrainerData.isEmpty())
                database.update(newTrainerData);
          }
	}
}