FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/Fitness_Trainer__c.object-meta.xml
<CustomObject>
    <description>List of Gym Trainers for Fitlife Pro</description>
    <label>Fitness Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fitness Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Assigned_Members__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Members__c</fullName>
    <label>Assigned Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Availability_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Availability_Schedule__c</fullName>
    <inlineHelpText>Please select any one of the slot.</inlineHelpText>
    <label>Availability Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Trainer Phone Number</description>
    <inlineHelpText>Phone number should be in numbers and can&#39;t exceed 10 digits</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Working_Status__c.field-meta.xml
<CustomField>
    <fullName>Working_Status__c</fullName>
    <description>Trainer is active or not</description>
    <label>Working Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In-active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>FLP-M-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>District__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OMR</fullName>
            </value>
            <value>
                <fullName>Navalur</fullName>
            </value>
            <value>
                <fullName>Guindy</fullName>
            </value>
            <value>
                <fullName>Saidapet</fullName>
            </value>
            <value>
                <fullName>Vadapalani</fullName>
            </value>
            <value>
                <fullName>Gandhipuram</fullName>
            </value>
            <value>
                <fullName>Saravanampatti</fullName>
            </value>
            <value>
                <fullName>R.S Puram</fullName>
            </value>
            <value>
                <fullName>Mettupalayam</fullName>
            </value>
            <value>
                <fullName>Perur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Fitness_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fitness Trainer</label>
    <referenceTo>Fitness_Trainer__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Member status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In-Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot__c</fullName>
    <label>Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/FitnessTrainerTriggerHandler_Test.cls
@isTest()
public class FitnessTrainerTriggerHandler_Test {
    
	@isTest()
    public static void testDoAction(){
        
        List<Fitness_Trainer__c> trainer = new List<Fitness_Trainer__c>();
        trainer.add(new Fitness_Trainer__c(Name = 'Rajan', Last_Name__c = 'Reddy', Phone_Number__c = '9658741235', Assigned_Members__c = 2,
                                                             Email__c = 'rajan@gmail.com', Working_Status__c = 'Active',
                                                             Availability_Schedule__c = 'Evening Slot - 4pm to 10pm', Salary__c = 50000));
        
        trainer.add(new Fitness_Trainer__c(Name = 'Praneel', Last_Name__c = 'Kumar', Phone_Number__c = '7778741235', 
                                                             Email__c = 'praneel@gmail.com', Working_Status__c = 'Active', Assigned_Members__c = 3,
                                                             Availability_Schedule__c = 'Evening Slot - 4pm to 10pm', Salary__c = 60000)); 
        
        trainer.add(new Fitness_Trainer__c(Name = 'Preksha', Last_Name__c = 'Kumari', Phone_Number__c = '9585858585', 
                                                             Email__c = 'preksha@gmail.com', Working_Status__c = 'In-Active', Assigned_Members__c = 2,
                                                             Availability_Schedule__c = 'Evening Slot - 4pm to 10pm', Salary__c = 70000));        
        insert trainer;
        Fitness_Trainer__c trainerRecord2 = [SELECT Id, Name, Assigned_Members__c, Working_Status__c FROM Fitness_Trainer__c WHERE Name = 'Praneel'];
        //List<Member__c> member = new List<Member__c>();
        Member__c member = new Member__c(First_Name__c = 'Ratan', Last_Name__c = 'Kumar ', Phone__c = '9685742547', 
            						Email__c = 'ratan'  + '@gmail.com', District__c = 'Chennai', Area__c = 'Navalur', Fitness_Trainer__c = trainerRecord2.Id,
                              		DOB__c = date.valueOf('1981-10-15'), Time_Slot__c = 'Evening Slot - 4pm to 10pm', Status__c = 'Active');
                   
        //member.add(new Member__c(First_Name__c = 'Anoop ', Last_Name__c = 'Kulkarni ', Phone__c = '9632587456', 
        //    					Email__c = 'anoop@gmail.com', District__c = 'Chennai', Area__c = 'Navalur', 
        //                        DOB__c = date.valueOf('1979-10-20'))); 
        Test.startTest();        
		insert member; 
     
        Member__c memberRecord1 = [SELECT Id, First_Name__c,Fitness_Trainer__c FROM Member__c WHERE First_Name__c = 'Ratan'];
        //system.debug('memberRecord1 :' + memberRecord1);
        Fitness_Trainer__c newTrainer = New Fitness_Trainer__c();
        Fitness_Trainer__c trainerRecord1 = [SELECT Id, Assigned_Members__c FROM Fitness_Trainer__c WHERE Name = 'Preksha'];
        newTrainer.Id = memberRecord1.Fitness_Trainer__c;
        newTrainer.Working_Status__c = 'In-Active'; 
        //system.debug('newTrainer :' + newTrainer);
        //system.debug('trainerRecord2 :' + trainerRecord2);
        update newTrainer;        
        test.stopTest();
        
        FitnessTrainerTriggerHandler trainerHandler = new FitnessTrainerTriggerHandler();
    	trainerHandler.doAction();
        
        Fitness_Trainer__c trainerRecord = [SELECT Id, Assigned_Members__c FROM Fitness_Trainer__c WHERE Id =: memberRecord1.Fitness_Trainer__c];
        system.debug('Assigned_Members__c: '+ trainerRecord.Assigned_Members__c);
        System.assertEquals(0, trainerRecord.Assigned_Members__c, 'Assigned Member count should match');        
    }  

}