FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/Fitness_Trainer__c.object-meta.xml
<CustomObject>
    <description>List of Gym Trainers for Fitlife Pro</description>
    <label>Fitness Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fitness Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Assigned_Members__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Members__c</fullName>
    <label>Assigned Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Working_Status__c.field-meta.xml
<CustomField>
    <fullName>Working_Status__c</fullName>
    <description>Trainer is active or not</description>
    <label>Working Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In-active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>FLP-M-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Member__c/fields/Fitness_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fitness Trainer</label>
    <referenceTo>Fitness_Trainer__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/FitnessTrainerTriggerHandler.cls
public class FitnessTrainerTriggerHandler {
    
    //Trigger Name : FitnessTrainerTrigger
    List<Fitness_Trainer__c> triggerNew;
    List<Fitness_Trainer__c> triggerOld;
    Map<Id,Fitness_Trainer__c> triggerNewMap;
    Map<Id,Fitness_Trainer__c> triggerOldMap;
    
    public FitnessTrainerTriggerHandler(){
        
        triggerNew = (List<Fitness_Trainer__c>)Trigger.New; // type cast from SObject to Member__c
        triggerOld = (List<Fitness_Trainer__c>)Trigger.Old;
        triggerNewMap = (Map<Id,Fitness_Trainer__c>)Trigger.NewMap;
        triggerOldMap = (Map<Id,Fitness_Trainer__c>)Trigger.OldMap;
    }
    
    public void doAction(){         
        
        SWITCH on Trigger.operationType{
            
            WHEN AFTER_INSERT{
                inActiveTrainer();  
            }
            WHEN AFTER_UPDATE{                
                inActiveTrainer(); 
            }                        
        }
    }
    
    public void inActiveTrainer(){        
        system.debug('Inside inActiveTrainer ');
        set<String> inActiveTrainer = new set<String>();
        List<Member__c> memberListUpdate = new List<Member__c>();
        for(Fitness_Trainer__c trainer : triggerNew){
            if(trainer.Working_Status__c == 'In-active' && trainer.Assigned_Members__c > 0){                
                inActiveTrainer.add(trainer.Id);				                
            }
        }
        if(!inActiveTrainer.isEmpty()){
            List<Fitness_Trainer__c> trainerList = [SELECT Id, Name, Assigned_Members__c 
                                                   FROM Fitness_Trainer__c
                                                   WHERE Working_Status__c = 'Active'
                                                   ORDER BY Assigned_Members__c
                                                   ];            
            List<Member__c> memberList = [SELECT Id, Fitness_Trainer__c
                                          FROM Member__c
                                          WHERE Fitness_Trainer__c in : inActiveTrainer                                               
                                         ];
            if(memberList.size() > 0){
                integer trainerListSize = trainerList.size();
                integer i = 0;
                system.debug('Member List Size : ' + memberList.size() + '   Trainer List Size : ' + trainerListSize);        
                for(Member__c memberRecord : memberList){            
                    Id tempTrainer = trainerList[Math.Mod (i++, trainerListSize)].Id;                    
                    Member__c member = new Member__c();
                    member.Fitness_Trainer__c = tempTrainer;
                    member.Id = memberRecord.Id;
                    memberListUpdate.add(member); 
                    //system.debug('Member List for Update : ' + memberListUpdate);
                }            
            }
               
            if(!memberListUpdate.isEmpty()){
                   database.update(memberListUpdate);
            }
        }
    }
}