FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/Fitness_Trainer__c.object-meta.xml
<CustomObject>
    <description>List of Gym Trainers for Fitlife Pro</description>
    <label>Fitness Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fitness Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Availability_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Availability_Schedule__c</fullName>
    <inlineHelpText>Please select any one of the slot.</inlineHelpText>
    <label>Availability Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Slot - 6am to 12pm</fullName>
            </value>
            <value>
                <fullName>Afternoon Slot - 12pm to 4pm</fullName>
            </value>
            <value>
                <fullName>Evening Slot - 4pm to 10pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Certifications__c.field-meta.xml
<CustomField>
    <fullName>Certifications__c</fullName>
    <label>Certifications</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACE Certified</fullName>
            </value>
            <value>
                <fullName>ISSA Certified</fullName>
            </value>
            <value>
                <fullName>NASM Certified</fullName>
            </value>
            <value>
                <fullName>NCSF Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Specialities__c.field-meta.xml
<CustomField>
    <fullName>Specialities__c</fullName>
    <label>Specialities</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Functional Training</fullName>
            </value>
            <value>
                <fullName>HIIT Workout</fullName>
            </value>
            <value>
                <fullName>Pilates</fullName>
            </value>
            <value>
                <fullName>Strength Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Fitness_Trainer__c/fields/Working_Status__c.field-meta.xml
<CustomField>
    <fullName>Working_Status__c</fullName>
    <description>Trainer is active or not</description>
    <label>Working Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In-active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/TrainerController.cls
public  without sharing class TrainerController {
    @AuraEnabled(cacheable=true)
    public static List<Fitness_Trainer__c> getTrainerListHandler() {
           return [SELECT 
                    Name,Last_Name__c,Photo__c,Specialities__c,
                    Certifications__c, Availability_Schedule__c 
                    FROM  Fitness_Trainer__c where Working_Status__c = 'Active'
                    ];  
   
    }
}