FitLifeProLatest/force-app/main/default/objects/Account/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

FitLifeProLatest/force-app/main/default/objects/Account/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

FitLifeProLatest/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FitLifeProLatest/force-app/main/default/objects/Trainer__c/fields/Count_of_Members__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Members__c</fullName>
    <label>Assigned Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FitLifeProLatest/force-app/main/default/classes/Test_MemberTriggerHandler.cls
@isTest
public class Test_MemberTriggerHandler {
	@isTest
    public static void testData()
    {
        Trainer__c trainer = new Trainer__c(Name = 'Trainer1');
        insert trainer;
         Account member = new Account(First_Name__c = 'Member Account',	Phone = '9823454567',  Trainer__c = trainer.Id);
         insert member;
         member.Trainer__c = null; 
        update member;
        trainer = [SELECT Id, Count_of_Members__c FROM Trainer__c WHERE Id = :trainer.Id];
        System.assertEquals(0, trainer.Count_of_Members__c, 'Count_of_Members__c should be updated to 0');
     }
    
  
}